XY_shapes:
  X: [8000, 11]
  Y: [18]
earlyStopOccured: 0
featureType: probes_quad
fitTime_min: 124.06279412110646
flattenSize: 11776
glob_epoch_duration_sec: [825.6060073375702, 1.6314476918784961]
glob_frame_duration_ms: [310.07647183462706, 0.6116556020863516]
hostName: cgpu16
hyperParams:
  batch_size: 64
  conv_filter: [64, 64, 256, 256, 256, 256, 256]
  conv_kernel: 5
  conv_repeat: 4
  dropFrac: 0.02
  fc_dims: [512, 512, 512, 496, 248, 62, 31]
  inp_batch_norm: true
  junk1: [1]
  lastAct: tanh
  lossName: mse
  myID: id134466260478
  numFeature: null
  optimizer: [nadam, 0.001, 1.1e-07]
  outAmpl: 1.2
  pool_len: 2
  reduceLR_factor: 0.10339426785106141
  steps: 4000
inpGen:
  train:
    batch_size: 64
    dataPath: /global/homes/b/balewski/prjn/neuronBBP-pack40kHzDisc/probe_quad/bbp153/
    fakeSteps: 4000
    fileIdxL: [14, 40, 5, 36, 49, 42, 23, 31, 9, 13, 0, 35, 3, 45, 17, 47, 18, 25,
      16, 37, 11, 4, 34, 33, 15, 46, 43, 44, 38, 21, 27, 41, 50, 22, 39, 6, 19, 30,
      1, 7, 51, 8]
    h5nameTemplate: bbp153.cellSpike_quad.data_*.h5
    name: train
    numFeature: null
    shuffle: true
    useDataFrac: 1.0
    x_y_aux: false
  val:
    batch_size: 64
    dataPath: /global/homes/b/balewski/prjn/neuronBBP-pack40kHzDisc/probe_quad/bbp153/
    fakeSteps: 500
    fileIdxL: [29, 32, 28, 2, 12]
    h5nameTemplate: bbp153.cellSpike_quad.data_*.h5
    name: val
    numFeature: null
    shuffle: true
    useDataFrac: 1.0
    x_y_aux: false
jobId: null
modelDesign: Raytune_design
modelLayerCnt: 90
modelWeightCnt: 13411203
state: model_trained
steps_per_epoch: 4000
totEpochs: 9
train_loss: 1.534213377147913
val_loss: 1.4810298252105714
