XY_shapes:
  X: [8000, 11]
  Y: [18]
earlyStopOccured: 0
featureType: probes_quad
fitTime_min: 202.42727898756664
flattenSize: 896
glob_epoch_duration_sec: [205.85643428358537, 10.543687368431009]
glob_frame_duration_ms: [2512.744792601059, 111.28553935558296]
hostName: cgpu11
hyperParams:
  batch_size: 128
  comment: HPO for bbp153-11probes using 4000 GPU hours
  conv_filter: [32, 64, 64, 64, 128, 128]
  conv_kernel: 7
  conv_repeat: 1
  dropFrac: 0.01
  fc_dims: [256, 256, 240]
  inp_batch_norm: true
  lastAct: tanh
  lossName: mse
  myId: id155018809965
  numFeature: null
  optimizer: [nadam, 0.001, 1.1e-07]
  outAmpl: 1.2
  pool_len: 3
  reduceLR_factor: 0.448298765780917
  steps: null
inpGen:
  train:
    batch_size: 128
    dataPath: data/bbp153/
    fakeSteps: null
    fileIdxL: [14, 40, 5, 36, 49, 42, 23, 31, 9, 13, 0, 35, 3, 45, 17, 47, 18, 25,
      16, 37, 11, 4, 34, 33, 15, 46, 43, 44, 38, 21, 27, 41, 50, 22, 39, 6, 19, 30,
      1, 7, 51, 8]
    h5nameTemplate: bbp153.cellSpike_quad.data_*.h5
    name: train
    numFeature: null
    shuffle: true
    useDataFrac: 1.0
    x_y_aux: false
  val:
    batch_size: 128
    dataPath: data/bbp153/
    fakeSteps: null
    fileIdxL: [29, 32, 28, 2, 12]
    h5nameTemplate: bbp153.cellSpike_quad.data_*.h5
    name: val
    numFeature: null
    shuffle: true
    useDataFrac: 1.0
    x_y_aux: false
jobId: 1145840/7/0
modelDesign: 603282_69_9_bbp153
modelLayerCnt: 33
modelWeightCnt: 608142
state: model_trained
steps_per_epoch: 4032
totEpochs: 59
train_loss: 0.03383650962958142
val_loss: 0.03452987935161218
